### ISSUE TITLE
Exception when open IntelliJ

### ISSUE THREAD

**Issue by afucher** [afucher/clojure-repl-intellij#69]
**Describe the bug**
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'action' of com/intellij/openapi/actionSystem/DefaultActionGroup.add must not be null
	at com.intellij.openapi.actionSystem.DefaultActionGroup.$$$reportNull$$$0(DefaultActionGroup.java)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.add(DefaultActionGroup.java)
	at com.github.ericdallo.clj4intellij.action$register_group_BANG_.invokeStatic(action.clj:67)
	at com.github.ericdallo.clj4intellij.action$register_group_BANG_.doInvoke(action.clj:51)
	at clojure.lang.RestFn.invoke(RestFn.java:805)
	at com.github.clojure_repl.intellij.extension.register_actions_startup$_runActivity.invokeStatic(register_actions_startup.clj:54)
	at com.github.clojure_repl.intellij.extension.register_actions_startup$_runActivity.invoke(register_actions_startup.clj:16)
	at com.github.clojure_repl.intellij.extension.RegisterActionsStartup.runActivity(Unknown Source)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:327)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:72)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$1$1.invoke(StartupManagerImpl.kt:264)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$1$1.invoke(StartupManagerImpl.kt:263)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:248)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:199)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:263)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:72)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2.invokeSuspend(StartupManagerImpl.kt:181)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**To Reproduce**
1. Update to version 1.1.0
2. Open IntelliJ

**Expected behavior**
No exceptions

**Environment (please complete the following information):**
 - IntelliJ Version: [e.g. IDEA 2023.2.5 (Community Edition) ]ntelliJ IDEA 2023.2.6 (Community Edition)
 - OS [e.g. MacOS, Windows, Linux] MacOS

**Additional context**

**Comment by afucher** [comment]
Closed by [#a47a8bf3e00869fd3f2f947a40217be82b48281d](https://github.com/afucher/clojure-repl-intellij/commit/a47a8bf3e00869fd3f2f947a40217be82b48281d)
