### ISSUE TITLE
Exception when running tests after opening a second project

### ISSUE THREAD

**Issue by afucher** [afucher/clojure-repl-intellij#74]
**Describe the bug**
When running tests sometimes it throws an exception.

```
com.intellij.util.IncorrectOperationException: Sorry but parent: Clojure test summary (class com.intellij.openapi.util.Disposer$2) has already been disposed (see the cause for stacktrace) so the child: com.intellij.openapi.wm.impl.content.ToolWindowContentUi$2@4b876b7a (class com.intellij.openapi.wm.impl.content.ToolWindowContentUi$2) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:43)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:161)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi.<init>(ToolWindowContentUi.java:212)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentManager$lambda$4(ToolWindowImpl.kt:175)
	at com.intellij.ui.content.impl.ContentManagerImpl.<init>(ContentManagerImpl.java:82)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentManager(ToolWindowImpl.kt:173)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.access$createContentManager(ToolWindowImpl.kt:74)
	at com.intellij.openapi.wm.impl.ToolWindowImpl$contentManager$1.invoke(ToolWindowImpl.kt:126)
	at com.intellij.openapi.wm.impl.ToolWindowImpl$contentManager$1.invoke(ToolWindowImpl.kt:125)
	at 
```
**To Reproduce**
1. Open a project
2. Runs tests
3. Open a second project
4. Try to run a test

**Expected behavior**
Tests should run correctly.

**Environment (please complete the following information):**
 - IntelliJ Version: [e.g. IDEA 2023.2.5 (Community Edition)]
 - OS [e.g. MacOS, Windows, Linux]: MacOS/Linux

**Comment by ericdallo** [comment]
I can't repro that, @afucher do you have the complete stacktrace mentioning cloure-lsp-intellij code?

**Comment by afucher** [comment]
I can get it, but probably just next week 😕

**Comment by afucher** [comment]
I'm not able to reproduce this anymore. @ericdallo did you change anything related to this?
