### ISSUE TITLE
When opening nREPL: java.lang.Exception: error when processing com.intellij.execution.process.ProcessEvent[source={}] by class com.github.clojure_repl.intellij.configuration.factory.remote.proxy_plus14239

### ISSUE THREAD

**Issue by devurandom** [afucher/clojure-repl-intellij#95]
**Describe the bug**

When opening a previously configured nREPL, I get `java.lang.Exception: error when processing com.intellij.execution.process.ProcessEvent[source={}] by class com.github.clojure_repl.intellij.configuration.factory.remote.proxy_plus14239`

**To Reproduce**
1. Don't start an nREPL server / socket
2. Have an nREPL configured with "Read from repl file"
3. Click the arrow to "Run"
4. Observe IntelliJ exception report

**Expected behavior**

nREPL opens or an error message is shown explaining why it cannot be opened.

**Environment (please complete the following information):**
 - IntelliJ Version: see below
 - OS: Linux

```
IntelliJ IDEA 2024.3.1 (Ultimate Edition)
Build #IU-243.22562.145, built on December 9, 2024
Licensed to [REDACTED]
Subscription is active until [REDACTED].
Runtime version: 21.0.5+8-b631.28 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.wl.WLToolkit
Linux 6.12.4-200.fc41.x86_64
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 8192M
Cores: 8
Registry:
  ide.experimental.ui=true
  i18n.locale=
  org.toml.json.schema=false
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (243.22562.180)
  org.jetbrains.plugins.go (243.22562.145)
  com.github.clojure-lsp (2.6.4)
  djblue.portal (0.58.4)
  com.intellij.grazie.pro (0.3.354)
  name.kropp.intellij.makefile (243.21565.122)
  com.intellij.plugins.watcher (243.22562.13)
  org.intellij.plugins.hcl (243.22562.13)
  PythonCore (243.22562.145)
  com.jetbrains.rust (243.22562.187)
  aws.toolkit.core (3.45-243)
  com.github.clojure-repl (1.6.0)
  com.jetbrains.space (243.21565.122)
  org.jetbrains.plugins.go-template (243.21565.122)
  com.intellij.ideolog (243.22562.180)
  PlantUML integration (7.11.2-IJ2023.2)
  com.intellij.datagen (243.21565.122)
  org.jetbrains.plugins.localization (243.21565.122)
  com.intellij.properties.bundle.editor (243.21565.122)
  Pythonid (243.22562.145)
  com.intellij.aqua (243.22562.155)
  com.intellij.ml.llm (243.22562.251.6)
  mobi.hsz.idea.gitignore (4.5.4)
  com.jetbrains.plugins.jade (243.21565.129)
  com.intellij.bigdatatools.core (243.22562.145)
  com.intellij.bigdatatools.binary.files (243.21565.129)
  com.intellij.bigdatatools.rfs (243.22562.145)
  com.intellij.tide (243.22562.164)
  mdx.js (243.21565.120)
  com.dmarcotte.handlebars (243.21565.122)
  deno (243.22562.13)
  to.bri.intellij.clubhouse (0.1.13)
  net.ashald.envfile (3.4.2)
  com.jetbrains.php (243.22562.164)
  aws.toolkit (3.45-243)
Kotlin: 243.22562.145-IJ
Current Desktop: KDE
```

**Additional context**

```
java.lang.Exception: error when processing com.intellij.execution.process.ProcessEvent[source={}] by class com.github.clojure_repl.intellij.configuration.factory.remote.proxy_plus14239
	at com.intellij.execution.process.ProcessHandler$2.startNotified(ProcessHandler.java:253)
	at com.intellij.execution.process.ProcessHandler.startNotify(ProcessHandler.java:57)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1$1$1.run(ExecutionManagerImpl.kt:316)
	at com.intellij.ui.AppUIUtil.invokeLaterIfProjectAlive(AppUIUtil.kt:200)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1$1.invoke(ExecutionManagerImpl.kt:297)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1$1.invoke(ExecutionManagerImpl.kt:296)
	at com.intellij.execution.impl.ExecutionManagerImplKt$sam$java_util_function_Consumer$0.accept(ExecutionManagerImpl.kt)
	at org.jetbrains.concurrency.DonePromise.onSuccess(promise.kt:480)
	at org.jetbrains.concurrency.DonePromise.onSuccess(promise.kt:449)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$$inlined$Runnable$1.run(Runnable.kt:31)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:236)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:25)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:198)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$2(AnyThreadWriteThreadingSupport.kt:217)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:216)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:842)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:421)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:117)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:675)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:573)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:355)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1045)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:916)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2(IdeEventQueue.kt:1045)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1054)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:109)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1054)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:395)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:578)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:751)
	at java.base/java.net.Socket.connect(Socket.java:686)
	at java.base/java.net.Socket.<init>(Socket.java:555)
	at java.base/java.net.Socket.<init>(Socket.java:324)
	at nrepl.core$connect.invokeStatic(core.clj:190)
	at nrepl.core$connect.doInvoke(core.clj:175)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at com.github.clojure_repl.intellij.nrepl.NREPLClient.start_BANG_(nrepl.clj:27)
	at com.github.clojure_repl.intellij.nrepl$start_client_BANG_.invokeStatic(nrepl.clj:73)
	at com.github.clojure_repl.intellij.nrepl$start_client_BANG_.doInvoke(nrepl.clj:70)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at com.github.clojure_repl.intellij.configuration.factory.base$repl_started.invokeStatic(base.clj:70)
	at com.github.clojure_repl.intellij.configuration.factory.base$repl_started.invoke(base.clj:69)
	at com.github.clojure_repl.intellij.configuration.factory.remote$setup_process$startNotified14240_impl__14243.invoke(remote.clj:48)
	at com.github.clojure_repl.intellij.configuration.factory.remote.proxy_plus14239.startNotified(Unknown Source)
	at com.intellij.execution.process.ProcessHandler$2.startNotified(ProcessHandler.java:247)
	... 54 more
```

There is no `.*repl*` file containing host or port information in the project directory, as far as I can tell.  The process with the nREPL server / socket is not running.

**Comment by afucher** [comment]
@devurandom can you share your IntelliJ configuration file? It should be: `.idea/workspace.xml` 
Just to make sure what is configured for this run. If you don't want to share the entire content, you can search for the specific entry, something like that:
```xml
<configuration name="local" type="clojure-repl" factoryName="clojure-repl-local">
  <option name="project" value="clojure-sample" />
  <method v="2" />
</configuration>
```

**Comment by afucher** [comment]
Closing due to inactivity.
